---
# Defines tasks to install and configure driveclient

- name: Include the OS specific varibles
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - driveclient
    - rackspace

- name: Check for APT repository
  stat: >
    path={{ driveclient_source }}
  register: source_path
  when: ansible_os_family == 'Debian'
  tags:
    - driveclient
    - rackspace

- name: Add APT key for Debian derivatives
  command: >
    sh -c 'wget -q "http://agentrepo.drivesrvr.com/debian/agentrepo.key" -O- | apt-key add -'
  when: source_path.stat.exists == false
  tags:
    - driveclient
    - rackspace

- name: Add APT repository for Debian derivatives
  template: >
    src=driveclient-list.j2
    dest={{ driveclient_source }}
    mode=0644 owner=root group=root
  when: ansible_os_family == 'Debian'
  tags:
    - driveclient
    - rackspace

- name: Install packages for Debian derivatives
  apt: >
    pkg={{ item }}
    update_cache=yes
    state=latest
  with_items: driveclient_packages
  when: ansible_os_family == 'Debian'
  tags:
    - driveclient
    - rackspace

- name: Configure the agent
  shell: >
    /usr/local/bin/driveclient --configure --apikey {{ driveclient_apikey }} --username {{ driveclient_username }}
    creates=/etc/driveclient/bootstrap.json
  tags:
    - driveclient
    - rackspace

- name: Start agent on server boot
  service: >
    name={{ driveclient_service }}
    state=started
    enabled=yes
  tags:
    - driveclient
    - rackspace
